In [22]:
#importation
import numpy as np
import pandas as pd
from textblob import TextBlob 
import re
import nltk
from pandas import DataFrame
from nrclex import NRCLex
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [23]:
filePath='C:/Users/pk/Desktop/projet/analyse/data/huawei.csv'
data=pd.read_csv(filePath)
data.columns=["date", "text"]
data.head(5)

                  date                                               text
0  2021-03-30 23:56:56  b'RT @CryptoWizardd: $mitx undervalued\n\nacti...
1  2021-03-30 23:56:44  b'RT @Tom_Fowdy: Boris Johnson:\n\n"Let\'s tur...
2  2021-03-30 23:56:10  b'RT @CryptoBoss1984: Another hidden gem find ...
3  2021-03-30 23:55:52  b'RT @Tom_Fowdy: Boris Johnson:\n\n"Let\'s tur...
4  2021-03-30 23:55:12  b'Boris Johnson:\n\n"Let\'s turn G7 into an an...

In [24]:
NAN = [(c, data[c].isna().mean()*100) for c in data]
NAN = pd.DataFrame(NAN, columns=["column_name", "percentage"])
NAN.sort_values("percentage", ascending=False)

  column_name  percentage
0        date         0.0
1        text         0.0

In [25]:
#**Drop NAN Values**
data =data.dropna()

In [26]:
#**Verify NAN Values**
NAN = [(c, data[c].isna().mean()*100) for c in data]
NAN = pd.DataFrame(NAN, columns=["column_name", "percentage"])
NAN.sort_values("percentage", ascending=False)

  column_name  percentage
0        date         0.0
1        text         0.0

In [27]:
#**Convert the data into lowercase**
data["Comment"]= data["text"].str.lower()

In [28]:
#**Word Tokenization and deleting punctuation**
AComment=[]
for comment in data["Comment"].apply(str):
    Word_Tok = []
    for word in  re.sub("\W"," ",comment ).split():
        Word_Tok.append(word)
    AComment.append(Word_Tok)

In [29]:
#**Add New Column to our data**
data["Word_Tok"]= AComment
data.head()

,date,text,Comment,Word_Tok
0,2021-03-30 23:56:56,b'RT @CryptoWizardd: $mitx undervalued\n\nacti...,b'rt @cryptowizardd: $mitx undervalued\n\nacti...,"[b, rt, cryptowizardd, mitx, undervalued, n, n..."
1,2021-03-30 23:56:44,"b'RT @Tom_Fowdy: Boris Johnson:\n\n""Let\'s tur...","b'rt @tom_fowdy: boris johnson:\n\n""let\'s tur...","[b, rt, tom_fowdy, boris, johnson, n, n, let, ..."
2,2021-03-30 23:56:10,b'RT @CryptoBoss1984: Another hidden gem find ...,b'rt @cryptoboss1984: another hidden gem find ...,"[b, rt, cryptoboss1984, another, hidden, gem, ..."
3,2021-03-30 23:55:52,"b'RT @Tom_Fowdy: Boris Johnson:\n\n""Let\'s tur...","b'rt @tom_fowdy: boris johnson:\n\n""let\'s tur...","[b, rt, tom_fowdy, boris, johnson, n, n, let, ..."
4,2021-03-30 23:55:12,"b'Boris Johnson:\n\n""Let\'s turn G7 into an an...","b'boris johnson:\n\n""let\'s turn g7 into an an...","[b, boris, johnson, n, n, let, s, turn, g7, in..."

In [30]:
#**Delete StopWords and lemmatize**
        
description_list =[]
for description in data['Word_Tok']:
   
    description=[word for word in description if not word in set(stopwords.words("english"))]
    lemma=nltk.WordNetLemmatizer()
    description=[lemma.lemmatize(word) for word in description]
    description=" ".join(description)
    description_list.append(description)

In [32]:
#**Add new Column: Comment after preprocessing**

data["CommentAferPreproc"]=description_list
data.head()

,date,text,Comment,Word_Tok,CommentAferPreproc
0,2021-03-30 23:56:56,b'RT @CryptoWizardd: $mitx undervalued\n\nacti...,b'rt @cryptowizardd: $mitx undervalued\n\nacti...,"[b, rt, cryptowizardd, mitx, undervalued, n, n...",b rt cryptowizardd mitx undervalued n nactive ...
1,2021-03-30 23:56:44,"b'RT @Tom_Fowdy: Boris Johnson:\n\n""Let\'s tur...","b'rt @tom_fowdy: boris johnson:\n\n""let\'s tur...","[b, rt, tom_fowdy, boris, johnson, n, n, let, ...",b rt tom_fowdy boris johnson n n let turn g7 a...
2,2021-03-30 23:56:10,b'RT @CryptoBoss1984: Another hidden gem find ...,b'rt @cryptoboss1984: another hidden gem find ...,"[b, rt, cryptoboss1984, another, hidden, gem, ...",b rt cryptoboss1984 another hidden gem find mi...
3,2021-03-30 23:55:52,"b'RT @Tom_Fowdy: Boris Johnson:\n\n""Let\'s tur...","b'rt @tom_fowdy: boris johnson:\n\n""let\'s tur...","[b, rt, tom_fowdy, boris, johnson, n, n, let, ...",b rt tom_fowdy boris johnson n n let turn g7 a...
4,2021-03-30 23:55:12,"b'Boris Johnson:\n\n""Let\'s turn G7 into an an...","b'boris johnson:\n\n""let\'s turn g7 into an an...","[b, boris, johnson, n, n, let, s, turn, g7, in...",b boris johnson n n let turn g7 anti china gro...

In [33]:
#**Sentiment Analysis with TextBlob**

senti_list = []
for i in data["CommentAferPreproc"]:
   # vs=te.get_emotion(i)
    vs = TextBlob(i).sentiment[0]
    if (vs > 0):
        senti_list.append('Positive')
    elif (vs < 0):
        senti_list.append('Negative')
    else:
        senti_list.append('Neutral')

In [34]:
#**Add Column: Sentiment**
data["sentiment"]=senti_list
data.head()

,date,text,Comment,Word_Tok,CommentAferPreproc,sentiment
0,2021-03-30 23:56:56,b'RT @CryptoWizardd: $mitx undervalued\n\nacti...,b'rt @cryptowizardd: $mitx undervalued\n\nacti...,"[b, rt, cryptowizardd, mitx, undervalued, n, n...",b rt cryptowizardd mitx undervalued n nactive ...,Neutral
1,2021-03-30 23:56:44,"b'RT @Tom_Fowdy: Boris Johnson:\n\n""Let\'s tur...","b'rt @tom_fowdy: boris johnson:\n\n""let\'s tur...","[b, rt, tom_fowdy, boris, johnson, n, n, let, ...",b rt tom_fowdy boris johnson n n let turn g7 a...,Neutral
2,2021-03-30 23:56:10,b'RT @CryptoBoss1984: Another hidden gem find ...,b'rt @cryptoboss1984: another hidden gem find ...,"[b, rt, cryptoboss1984, another, hidden, gem, ...",b rt cryptoboss1984 another hidden gem find mi...,Positive
3,2021-03-30 23:55:52,"b'RT @Tom_Fowdy: Boris Johnson:\n\n""Let\'s tur...","b'rt @tom_fowdy: boris johnson:\n\n""let\'s tur...","[b, rt, tom_fowdy, boris, johnson, n, n, let, ...",b rt tom_fowdy boris johnson n n let turn g7 a...,Neutral
4,2021-03-30 23:55:12,"b'Boris Johnson:\n\n""Let\'s turn G7 into an an...","b'boris johnson:\n\n""let\'s turn g7 into an an...","[b, boris, johnson, n, n, let, s, turn, g7, in...",b boris johnson n n let turn g7 anti china gro...,Neutral

In [35]:
data.to_csv("C:/Users/pk/Desktop/projet/analyse/out_data/TweetHuawei.csv")

In [36]:
text=" ".join(data['CommentAferPreproc'])
text_object = NRCLex(text)

In [44]:
sentiment_scores = pd.DataFrame(list(text_object.raw_emotion_scores.items()))
sentiment_scores = sentiment_scores.rename(columns={0: "Sentiment", 1: "Count"})
sentiment_scores
sentiment_scores.to_csv('C:/Users/pk/Desktop/projet/analyse/out_data/tweetCountHuawei.csv')

In [42]:
sentiment_words = pd.DataFrame(list(text_object.affect_dict.items()),columns = ['words','sentiments'])
sentiment_words

         words                                         sentiments
0         team                                            [trust]
1        array                                         [positive]
2        build                                         [positive]
3       hidden                                         [negative]
4          gem                                    [joy, positive]
..         ...                                                ...
628  associate                                  [positive, trust]
629      junta                                         [negative]
630    endless  [anger, fear, joy, negative, positive, sadness...
631  desperate                                         [negative]
632       grow               [anticipation, joy, positive, trust]

[633 rows x 2 columns]

In [17]:
sentiment = sentiment_scores['Sentiment'].to_list()
sentiment

['trust',
 'positive',
 'negative',
 'joy',
 'anticipation',
 'anger',
 'disgust',
 'fear',
 'sadness',
 'surprise']

In [18]:
for y in sentiment:
    sentiment_words[y] = 9
sentiment_words

,words,sentiments,trust,positive,negative,joy,anticipation,anger,disgust,fear,sadness,surprise
0,team,[trust],9,9,9,9,9,9,9,9,9,9
1,array,[positive],9,9,9,9,9,9,9,9,9,9
2,build,[positive],9,9,9,9,9,9,9,9,9,9
3,hidden,[negative],9,9,9,9,9,9,9,9,9,9
4,gem,"[joy, positive]",9,9,9,9,9,9,9,9,9,9
...,...,...,...,...,...,...,...,...,...,...,...,...
628,associate,"[positive, trust]",9,9,9,9,9,9,9,9,9,9
629,junta,[negative],9,9,9,9,9,9,9,9,9,9
630,endless,"[anger, fear, joy, negative, positive, sadness...",9,9,9,9,9,9,9,9,9,9
631,desperate,[negative],9,9,9,9,9,9,9,9,9,9
632,grow,"[anticipation, joy, positive, trust]",9,9,9,9,9,9,9,9,9,9

In [19]:
a=0
for i in sentiment_words['sentiments']: 
    for y in sentiment:
        sentiment_words[y][a] = int(y in i)
    a=a+1

C:\Users\pk\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [20]:
sentiment_words.head(5)

,words,sentiments,trust,positive,negative,joy,anticipation,anger,disgust,fear,sadness,surprise
0,team,[trust],1,0,0,0,0,0,0,0,0,0
1,array,[positive],0,1,0,0,0,0,0,0,0,0
2,build,[positive],0,1,0,0,0,0,0,0,0,0
3,hidden,[negative],0,0,1,0,0,0,0,0,0,0
4,gem,"[joy, positive]",0,1,0,1,0,0,0,0,0,0

In [21]:
for y in sentiment:
    word_list = sentiment_words[sentiment_words[y]== 1].words.head(10)
    print(f"Sentiment:{y}")
    print(f"{word_list.values}\n")

Sentiment:trust
['team' 'cap' 'fundamental' 'efficient' 'asserting' 'trade' 'elite'
 'sympathetic' 'ambassador' 'legal']

Sentiment:positive
['array' 'build' 'gem' 'fundamental' 'standing' 'prime' 'patent'
 'efficient' 'electricity' 'traditional']

Sentiment:negative
['hidden' 'allegation' 'lawyer' 'small' 'war' 'threat' 'argument' 'vote'
 'pose' 'payment']

Sentiment:joy
['gem' 'elite' 'sympathetic' 'vote' 'share' 'success' 'cash' 'good'
 'money' 'white']

Sentiment:anticipation
['cap' 'time' 'efficient' 'network' 'court' 'elite' 'vote' 'continue'
 'acquiring' 'ram']

Sentiment:anger
['allegation' 'lawyer' 'court' 'threat' 'argument' 'vote' 'broken' 'hate'
 'shoot' 'ram']

Sentiment:disgust
['lawyer' 'hate' 'toxic' 'john' 'crap' 'ridiculous' 'default' 'powerful'
 'politic' 'damn']

Sentiment:fear
['lawyer' 'court' 'war' 'sympathetic' 'threat' 'giant' 'broken' 'case'
 'hate' 'shoot']

Sentiment:sadness
['sympathetic' 'vote' 'broken' 'case' 'hate' 'losing' 'restriction'
 'music' 'late' 'default']

Sentiment:surprise
['vote' 'steady' 'guess' 'good' 'money' 'unique' 'winner' 'slam'
 'unexpected' 'shopping']